name: dapt
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_1
  - addict=2.4.0=pyhd8ed1ab_2
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - einops=0.8.0=pyhd8ed1ab_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - grpcio=1.62.2=py310h6a678d5_0
  - h5py=3.12.1=py310hc0802c4_0
  - hdf5=1.12.1=h2b7332f_3
  - huggingface_hub=0.26.5=pyhd8ed1ab_1
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_1
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurl=7.88.1=h251f7ec_2
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm11=11.1.0=h9e868ea_6
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - pillow=11.0.0=py310hcea889d_1
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plyfile=1.1=pyhd8ed1ab_0
  - protobuf=4.25.3=py310h0e2eeba_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python_abi=3.10=2_cp310
  - pytorch=2.3.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cluster=1.6.3=py310_torch_2.3.0_cu118
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.3.0_cu118
  - pytorch-sparse=0.6.18=py310_torch_2.3.0_cu118
  - pyyaml=6.0.2=py310h5eee18b_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - safetensors=0.4.5=py310h505e2c1_0
  - scipy=1.11.4=py310h5f9d8c6_0
  - setuptools=75.1.0=py310h06a4308_0
  - sharedarray=3.2.4=py310hf462985_2
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py310h6c63255_2
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - termcolor=2.5.0=pyhd8ed1ab_1
  - timm=1.0.12=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.3.0=py310_cu118
  - torchtriton=2.3.0=py310
  - torchvision=0.18.0=py310_cu118
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - werkzeug=3.0.6=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.40.1=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - blinker==1.9.0
      - ccimport==0.4.4
      - chumpy==0.70
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cumm-cu118==0.7.11
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - fire==0.7.0
      - flash-attn==2.7.2.post1
      - flask==3.0.3
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lark==1.2.2
      - llvmlite==0.43.0
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - multidict==6.1.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.3
      - numba==0.60.0
      - open3d==0.18.0
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - parso==0.8.4
      - pccm==0.4.16
      - pexpect==4.9.0
      - plotly==5.24.1
      - portalocker==3.0.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==2.13.6
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pyquaternion==0.9.9
      - pytz==2024.2
      - referencing==0.35.1
      - retrying==1.3.4
      - rpds-py==0.22.3
      - scikit-learn==1.6.0
      - smplx==0.1.28
      - spconv-cu118==2.3.8
      - stack-data==0.6.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - torch-geometric==2.6.1
      - traitlets==5.14.3
      - tzdata==2024.2
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
      - pointcept_src/libs/pointops
      - pointnet2_src/pointnet2_ops_lib
prefix: /opt/conda/envs/dapt
